{
 "title": "Medical Supply Chain Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vehicle Sensor Data",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\r\n    vehicle_id,\r\n    temperature,\r\n    humidity,\r\n    radiation,\r\n    CASE\r\n        WHEN violation_flag = 'true' THEN 'RED'\r\n        ELSE 'GREEN'\r\n    END AS violation_status\r\nFROM \"druid-flagged-sensor-data\"\r\nWHERE \"__time\" >= CURRENT_TIMESTAMP - INTERVAL 7 SECOND\r\nORDER BY \"__time\" \r\n\r\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\r\\n    vehicle_id,\\r\\n    temperature,\\r\\n    humidity,\\r\\n    radiation,\\r\\n    CASE\\r\\n        WHEN violation_flag = 'true' THEN 'RED'\\r\\n        ELSE 'GREEN'\\r\\n    END AS violation_status\\r\\nFROM \\\"druid-flagged-sensor-data\\\"\\r\\nWHERE \\\"__time\\\" >= CURRENT_TIMESTAMP - INTERVAL 7 SECOND\\r\\nORDER BY \\\"__time\\\" \\r\\n\\r\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Inventory Levels",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT warehouse_id, MAX(quantity) AS quantity\nFROM \"inventory-updates-data\"\nWHERE \"__time\" >= CURRENT_TIMESTAMP - INTERVAL 20 SECOND\nGROUP BY warehouse_id",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT warehouse_id, MAX(quantity) AS quantity\\nFROM \\\"inventory-updates-data\\\"\\nWHERE \\\"__time\\\" >= CURRENT_TIMESTAMP - INTERVAL 20 SECOND\\nGROUP BY warehouse_id\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{\"contextParameters\":[{\"name\":\"enableWindowing\",\"value\":\"true\"}]}}",
     "settings": {
      "contextParameters": [
       { "name": "enableWindowing", "value": "true" }
      ]
     }
    }
   ]
  },
  {
   "title": "TOTAL ORDERS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT COUNT(*)\nFROM \"confirmed-orders-list\"\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT COUNT(*)\\nFROM \\\"confirmed-orders-list\\\"\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "No. of Delayed Orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT COUNT(*)\r\nFROM \"confirmed-orders-list\"\r\nWHERE TIMESTAMPDIFF(SECOND, \r\n    TIME_PARSE(\"estimated_delivery\", 'yyyy-MM-dd HH:mm:ss'), \r\n    TIME_PARSE(\"expected_delivery\", 'yyyy-MM-dd HH:mm:ss')) > (1 * 24 * 3600 + 20 * 3600)\r\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT COUNT(*)\\r\\nFROM \\\"confirmed-orders-list\\\"\\r\\nWHERE TIMESTAMPDIFF(SECOND, \\r\\n    TIME_PARSE(\\\"estimated_delivery\\\", 'yyyy-MM-dd HH:mm:ss'), \\r\\n    TIME_PARSE(\\\"expected_delivery\\\", 'yyyy-MM-dd HH:mm:ss')) > (1 * 24 * 3600 + 20 * 3600)\\r\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Vaccine Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 12 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT vaccine_id, SUM(quantity)\nFROM \"confirmed-orders-list\"\nGROUP BY vaccine_id\nORDER BY vaccine_id",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT vaccine_id, SUM(quantity)\\nFROM \\\"confirmed-orders-list\\\"\\nGROUP BY vaccine_id\\nORDER BY vaccine_id\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Predicted Demand",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT vaccine_id, MAX(Predicted_Demand)\nFROM \"inventory-predictions-data\"\nWHERE \"__time\" >= CURRENT_TIMESTAMP - INTERVAL 5 SECOND\nGROUP BY vaccine_id",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT vaccine_id, MAX(Predicted_Demand)\\nFROM \\\"inventory-predictions-data\\\"\\nWHERE \\\"__time\\\" >= CURRENT_TIMESTAMP - INTERVAL 5 SECOND\\nGROUP BY vaccine_id\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Ongoing Orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT COUNT(*)\r\nFROM \"confirmed-orders-list\"\r\nWHERE \"estimated_delivery\" > CURRENT_TIMESTAMP \r\n\r\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT COUNT(*)\\r\\nFROM \\\"confirmed-orders-list\\\"\\r\\nWHERE \\\"estimated_delivery\\\" > CURRENT_TIMESTAMP \\r\\n\\r\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Inventory Anomalies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT COUNT(*)\nFROM \"inventory-predictions-data\"\nWHERE \"Anomaly_Score\">=0.5",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT COUNT(*)\\nFROM \\\"inventory-predictions-data\\\"\\nWHERE \\\"Anomaly_Score\\\">=0.5\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}